steps:
  - label: ':console: Upload'
    key: 'package'
    command:
      - "echo 'Hello'"
    # artifact_paths:
    #   - 'README.md'
    #   - 'app/build/outputs/bundle/**/*.aab'
    plugins:
      - docker-compose#v3.10.0:
          run: fastlane
      - artifacts#v1.5.0:
          upload:
            from: '**/*.aab'
            to: 'build'

  - command: 'echo "+++ Files" && ls -alR'
    depends_on: 'package'
    plugins:
      - docker-compose#v3.10.0:
          run: fastlane
      - artifacts#v1.5.0:
          download: '*.aab'
          step: 'package'

  - input: ':rocket: Input 1'
    depends_on: 'package'
    key: 'input-1'
    fields:
      - text: 'Input 1'
        key: 'field-input-1'

  - input: ':rocket: Input 2'
    depends_on: 'package'
    key: 'input-2'
    fields:
      - text: 'Input 2'
        key: 'field-input-2'

  - label: 'Command on input 1'
    depends_on: 'input-1'
    command: "echo 'Hello input 1'"

  - label: 'Command on input 2'
    depends_on: 'input-2'
    command: "echo 'Hello input 2'"
